services:
  - type: web
    name: portifio
    env: node
    buildCommand: npm install && npx drizzle-kit generate:pg && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
    buildFilter:
      paths:
      - client/**
      - server/**
      - shared/**
      - migrations/**
      - package.json
      - package-lock.json
      - tsconfig.json
      - vite.config.ts
    disk:
      name: tmp
      mountPath: /tmp
    autoDeploy: true